## E0703 (bad-exception-context)

### :x: Problematic code:

```python
# to be addded
```

### :heavy_check_mark: Correct code:

```python
# to be added
```

### Rationale:

 *Exception context set to something which is not an exception, nor None*
  Used when using the syntax "raise ... from ...", where the exception context
  is not an exception, nor None. This message belongs to the exceptions
  checker.



### Related resources:

- [Testcases](#)
- [Issue Tracker](https://github.com/PyCQA/pylint/issues?q=is%3Aissue+%22bad-exception-context%22+OR+%22E0703%22)
