## E0104 (return-outside-function)

### :x: Problematic code:

```python
# to be addded
```

### :heavy_check_mark: Correct code:

```python
# to be added
```

### Rationale:

 *Return outside function*
  Used when a "return" statement is found outside a function or method. This
  message belongs to the basic checker.



### Related resources:

- [Testcases](#)
- [Issue Tracker](https://github.com/PyCQA/pylint/issues?q=is%3Aissue+%22return-outside-function%22+OR+%22E0104%22)
