## W1645 (exception-message-attribute)

### :x: Problematic code:

```python
# to be addded
```

### :heavy_check_mark: Correct code:

```python
# to be added
```

### Rationale:

 *Exception.message removed in Python 3*
  Used when the message attribute is accessed on an Exception. Use
  str(exception) instead. This message belongs to the python3 checker.



### Related resources:

- [Testcases](#)
- [Issue Tracker](https://github.com/PyCQA/pylint/issues?q=is%3Aissue+%22exception-message-attribute%22+OR+%22W1645%22)
