## W1662 (comprehension-escape)

### :x: Problematic code:

```python
# to be addded
```

### :heavy_check_mark: Correct code:

```python
# to be added
```

### Rationale:

 *Using a variable that was bound inside a comprehension*
  Emitted when using a variable, that was bound in a comprehension handler,
  outside of the comprehension itself. On Python 3 these variables will be
  deleted outside of the comprehension. This message belongs to the python3
  checker.



### Related resources:

- [Testcases](#)
- [Issue Tracker](https://github.com/PyCQA/pylint/issues?q=is%3Aissue+%22comprehension-escape%22+OR+%22W1662%22)
